name: magic_slides
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.4.3
  get_it: ^9.0.5
  go_router: ^10.2.0
  http: ^1.6.0
  lottie: ^3.3.2
  path_provider: ^2.1.5
  share_plus: ^10.1.2
  shared_preferences: ^2.5.3
  statemachine:
    git:
      url: https://github.com/ashlesh-md/statemachine.git
      ref: main
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/lotties/loading.zip
    - assets/dummy_response.json

  fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-Regular.ttf
      - asset: assets/fonts/Inter-Medium.ttf
      - asset: assets/fonts/Inter-SemiBold.ttf
      - asset: assets/fonts/Inter-Bold.ttf
